name: homigo_sdk_firebase
description: "Optional Firebase integrations for HomiGo SDK, including authentication, messaging, analytics, Crashlytics, and Remote Config."
version: 1.0.1
homepage: https://github.com/traikeyy-cmd/homigo-sdk
repository: https://github.com/traikeyy-cmd/homigo-sdk/tree/main/packages/homigo_sdk_firebase
issue_tracker: https://github.com/traikeyy-cmd/homigo-sdk/issues

topics:
  - firebase
  - authentication
  - push-notifications
  - analytics
  - crash-reporting

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_analytics: ^12.4.6
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  firebase_crashlytics: ^5.2.7
  firebase_messaging: ^16.5.0
  firebase_remote_config: ^6.5.6
  flutter:
    sdk: flutter
  homigo_sdk: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
